# AUTOGENERATED! DO NOT EDIT! File to edit: appMinima.ipynb.

# %% auto 0
__all__ = ['path_test', 'dls_test', 'learn_test', 'categories', 'image', 'label', 'examples', 'intf', 'is_cat', 'classify_image']

# %% appMinima.ipynb 3
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

# %% appMinima.ipynb 8
path_test = untar_data(URLs.PETS)/'images'

dls_test = ImageDataLoaders.from_name_func('.',
    get_image_files(path_test), valid_pct=0.2, seed=42,
    label_func=is_cat,
    item_tfms=Resize(192, method='squish'))

# %% appMinima.ipynb 9
learn_test = vision_learner(dls_test, resnet18, metrics=error_rate)

# %% appMinima.ipynb 10
learn_test.load('model.pkl')

# %% appMinima.ipynb 12
categories = ('Dog', 'Cat')

def classify_image(img):
    pred,idx,probs = learn_test.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% appMinima.ipynb 14
image = gr.Image()
label = gr.Label()
examples = ['dog.jpg', 'cat.jpg', 'dunno.jpg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
